# Generated by Django 3.2.7 on 2023-12-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='Rent_per_momth',
            new_name='Rent_per_month',
        ),
        migrations.AddField(
            model_name='properties',
            name='Bath_Rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='Bed_Rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='Squre_Feet',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
