# Generated by Django 3.2.14 on 2023-12-02 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0002_auto_20231202_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Landlord', models.CharField(max_length=11)),
                ('date', models.DateField(auto_now_add=True)),
                ('Tenent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.properties')),
            ],
        ),
    ]
