# Generated by Django 3.1.1 on 2024-03-22 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0006_properties_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PropertiesSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('office', 'office'), ('Villa', 'Villa')], default='House', max_length=50)),
                ('Squre_Feet', models.FloatField(blank=True, null=True)),
                ('Bed_Rooms', models.IntegerField(blank=True, null=True)),
                ('Bath_Rooms', models.IntegerField(blank=True, null=True)),
                ('Place', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
                ('District', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('Description', models.CharField(max_length=1000)),
                ('Image', models.FileField(upload_to='Property_image')),
                ('Status', models.BooleanField(default=True)),
                ('User_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
